In [1]:
import numpy as np
import pandas as pd
from sigmoid import sigmoid
from cost_function import *
import scipy.optimize as opt
import os
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from predict import *
from sklearn.metrics import *

In [2]:
PATH_INPUT = os.getcwd() + '/inputs/'

### Implementação das funções de custo

In [263]:
def cal_cost(theta, X, y):
    """
        :input: theta -
        :input: X -
        :input: y -
        
        :return: cost
    """
    m = len(y)
    
    predictions = X.dot(theta)
    cost = (1/2*m) * np.sum(np.square(predictions-y))
    
    return cost

In [264]:
def gradient_descent(theta,X,y,learning_rate=0.01,iterations=100):
    """
        :input: X - 
        :input: X - 
        :input: X - 
        :input: X - 
        :input: X - 
        
        :return: theta - 
        :return: cost_history - 
        :return: theta_history -         
    """
    m = len(y)
    cost_history = np.zeros(iterations)
    theta_history = np.zeros((iterations,3))
    for it in range(iterations):
        prediction = np.dot(X,theta)
        theta = theta -(1/m)*learning_rate*( X.T.dot((prediction - y)))
        theta_history[it,:] =theta.T
        cost_history[it]  = cal_cost(theta,X,y)

    return theta, cost_history, theta_history

In [286]:
def minibatch_gradient_descent(X,y,theta,learning_rate=0.01,iterations=10,batch_size =20):
    '''
    X    = Matrix of X without added bias units
    y    = Vector of Y
    theta=Vector of thetas np.random.randn(j,1)
    learning_rate 
    iterations = no of iterations

    Returns the final theta vector and array of cost history over no of iterations
    '''
    m = len(y)
    cost_history = np.zeros(iterations)
    n_batches = int(m/batch_size)

    for it in range(iterations):
        cost =0.0
        indices = np.random.permutation(m)
        X = X[indices]
        y = y[indices]
        for i in range(0,m,batch_size):
            X_i = X[i:i+batch_size]
            y_i = y[i:i+batch_size]

            X_i = np.c_[np.ones(len(X_i)),X_i]

            prediction = np.dot(X_i,theta)

            theta = theta -(1/m)*learning_rate*( X_i.T.dot((prediction - y_i)))
            cost += cal_cost(theta,X_i,y_i)
        cost_history[it]  = cost

    return theta, cost_history

In [46]:
def predict(theta, X):

    predict = sigmoid(np.dot(X, theta))
    predict = 1 * (predict >= 0.5)

    return predict

### Load do dataset de treino e separacao dos dados

Load do cvs com o treino feito anteriormente

In [298]:
df_treino = pd.read_csv(PATH_INPUT+'training-data.csv')
df_treino

character_name  episode_appearance_count  kill_count  dead
0            Addam Marbrand                         1           0     0
1             Aeron Greyjoy                         2           0     0
2                      Akho                         3           0     1
3            Alliser Thorne                        19           1     1
4           Alton Lannister                         3           0     1
5             Alys Karstark                         4           0     0
6               Amory Lorch                         3           1     1
7                     Anguy                         6           0     0
8                Areo Hotah                         6           0     1
9                    Armeca                         4           0     0
10                   Arthur                         2           0     0
11             Arthur Dayne                         1           0     1
12               Arya Stark                        55          11     0
13                 Baby Sam                        20           0     0
14            Balon Greyjoy                         4           0     1
15          Barristan Selmy                        25           0     1
16             Benjen Stark                         6           0     1
17         Beric Dondarrion                        12           0     1
18                   Bianca                         2           0     0
19                    Biter                         3           0     1
20             Black Lorren                         4           0     0
21      Black Walder Rivers                         5           1     1
22                   Bobono                         2           0     0
23              Bowen Marsh                         8           1     1
24               Bran Stark                        37           0     0
25                     Brea                         1           0     0
26         Brienne of Tarth                        38           3     0
27                    Bronn                        34           3     0
28              Brother Ray                         1           0     1
29            Brynden Tully                         7           0     0
..                      ...                       ...         ...   ...
324       Viserys Targaryen                         5           0     1
325            Walda Bolton                         5           0     1
326             Walder Frey                         6           0     1
327                  Wallen                         1           0     1
328                 Warlock                         1           0     0
329            Waymar Royce                         1           0     1
330            White Walker                        14           0     0
331            White Walker                        14           0     1
332            White Walker                        14           1     1
333     Wight Wildling Girl                         2           0     0
334         Wildling Rioter                         1           0     0
335                    Will                         1           0     1
336        Willem Lannister                         2           0     1
337           Wine Merchant                         1           0     0
338     Winterfell Shepherd                         2           0     0
339                 Wun Wun                         5           0     1
340                  Wyllis                         2           0     0
341        Xaro Xhoan Daxos                         5           0     1
342            Yara Greyjoy                        15           0     0
343        Yezzan zo Qaggaz                         4           0     0
344                 Ygritte                        17           4     1
345              Yohn Royce                        11           0     0
346                   Yoren                         7           0     1
347      Young Benjen Stark                         2

Normaliza o X

In [299]:
std_scale = preprocessing.MinMaxScaler()

df_treino['episode_appearance_count'] = std_scale.fit_transform((df_treino['episode_appearance_count'].values).reshape((-1,1)))
df_treino['kill_count'] = std_scale.fit_transform((df_treino['kill_count'].values).reshape((-1,1)))

df_treino

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


character_name  episode_appearance_count  kill_count  dead
0            Addam Marbrand                  0.000000    0.000000     0
1             Aeron Greyjoy                  0.016129    0.000000     0
2                      Akho                  0.032258    0.000000     1
3            Alliser Thorne                  0.290323    0.071429     1
4           Alton Lannister                  0.032258    0.000000     1
5             Alys Karstark                  0.048387    0.000000     0
6               Amory Lorch                  0.032258    0.071429     1
7                     Anguy                  0.080645    0.000000     0
8                Areo Hotah                  0.080645    0.000000     1
9                    Armeca                  0.048387    0.000000     0
10                   Arthur                  0.016129    0.000000     0
11             Arthur Dayne                  0.000000    0.000000     1
12               Arya Stark                  0.870968    0.785714     0
13                 Baby Sam                  0.306452    0.000000     0
14            Balon Greyjoy                  0.048387    0.000000     1
15          Barristan Selmy                  0.387097    0.000000     1
16             Benjen Stark                  0.080645    0.000000     1
17         Beric Dondarrion                  0.177419    0.000000     1
18                   Bianca                  0.016129    0.000000     0
19                    Biter                  0.032258    0.000000     1
20             Black Lorren                  0.048387    0.000000     0
21      Black Walder Rivers                  0.064516    0.071429     1
22                   Bobono                  0.016129    0.000000     0
23              Bowen Marsh                  0.112903    0.071429     1
24               Bran Stark                  0.580645    0.000000     0
25                     Brea                  0.000000    0.000000     0
26         Brienne of Tarth                  0.596774    0.214286     0
27                    Bronn                  0.532258    0.214286     0
28              Brother Ray                  0.000000    0.000000     1
29            Brynden Tully                  0.096774    0.000000     0
..                      ...                       ...         ...   ...
324       Viserys Targaryen                  0.064516    0.000000     1
325            Walda Bolton                  0.064516    0.000000     1
326             Walder Frey                  0.080645    0.000000     1
327                  Wallen                  0.000000    0.000000     1
328                 Warlock                  0.000000    0.000000     0
329            Waymar Royce                  0.000000    0.000000     1
330            White Walker                  0.209677    0.000000     0
331            White Walker                  0.209677    0.000000     1
332            White Walker                  0.209677    0.071429     1
333     Wight Wildling Girl                  0.016129    0.000000     0
334         Wildling Rioter                  0.000000    0.000000     0
335                    Will                  0.000000    0.000000     1
336        Willem Lannister                  0.016129    0.000000     1
337           Wine Merchant                  0.000000    0.000000     0
338     Winterfell Shepherd                  0.016129    0.000000     0
339                 Wun Wun                  0.064516    0.000000     1
340                  Wyllis                  0.016129    0.000000     0
341        Xaro Xhoan Daxos                  0.064516    0.000000     1
342            Yara Greyjoy                  0.225806    0.000000     0
343        Yezzan zo Qaggaz                  0.048387    0.000000     0
344                 Ygritte                  0.258065    0.285714     1
345              Yohn Royce                  0.161290    0.000000     0
346                   Yoren                  0.096774    0.000000     1
347      Young Benjen Stark                  0.016129

Carrega o X e y

In [300]:
X = df_treino.iloc[:,1:3]
y = df_treino.iloc[:,3:]

Split do dataframe em treino e teste

In [301]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, shuffle=True)

### Procurando o theta ...

In [302]:
x_theta = np.c_[np.ones((X_train.shape[0],1)),X_train.values]
y_theta = y_train.values

In [303]:
initial_theta = np.random.rand(3,1)
initial_theta

array([[0.01728661],
       [0.93632198],
       [0.81966902]])

In [304]:
theta_grad, cost_history, theta_history = gradient_descent(initial_theta,x_theta,y_theta,0.001,1000000)
theta_grad

array([[-0.12905073],
       [ 0.10194246],
       [-0.33660882]])

In [305]:
cost_history[-1]

14045.738223882996

In [279]:
initial_theta_ba = np.random.rand(3,1)
initial_theta_ba

array([[0.42203653],
       [0.71131459],
       [0.53375735]])

In [311]:
theta_batch, c_history = minibatch_gradient_descent(X_train.values,y_theta,initial_theta_ba,0.001,10000,10)
theta_batch

array([[0.39831732],
       [0.45004059],
       [0.36964516]])

In [312]:
c_history[-1]

451.82290153355973

### Predict com o dataset de teste para o método do gradiente descendente

In [306]:
x_predict = np.c_[np.ones((X_test.shape[0],1)),X_test.values]

In [307]:
y_pred = predict(theta_grad, x_predict)

In [308]:
confusion_matrix_grad = confusion_matrix(y_test, y_pred)
print("Matriz de Confusão para o metodo do gradiente descendente:\n", confusion_matrix_grad)

Matriz de Confusão para o metodo do gradiente descendente:
 [[9 0]
 [9 0]]


In [309]:
precision_grad,recall_grad,fscore_grad,support_grad = precision_recall_fscore_support(y_test,y_pred)
print("Precisao para o metodo do gradiente descendente: ", precision_grad)
print("Recall para o metodo do gradiente descendente: ", recall_grad)
print("F-Score para o metodo do gradiente descendente: ", fscore_grad)
print("Support para o metodo do gradiente descendente: ", support_grad)

Precisao para o metodo do gradiente descendente:  [0.5 0. ]
Recall para o metodo do gradiente descendente:  [1. 0.]
F-Score para o metodo do gradiente descendente:  [0.66666667 0.        ]
Support para o metodo do gradiente descendente:  [9 9]


/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [310]:
acc_grad = accuracy_score(y_test, y_pred)
print("Acuracia para o metodo do gradiente descendente: ", acc_grad)

Acuracia para o metodo do gradiente descendente:  0.5


### Predict com o dataset de teste para o método do batch

In [313]:
x_predict = np.c_[np.ones((X_test.shape[0],1)),X_test.values]

In [314]:
y_pred = predict(theta_batch, x_predict)

In [315]:
confusion_matrix_batch = confusion_matrix(y_test, y_pred)
print("Matriz de Confusão para o metodo do gradiente batch:\n", confusion_matrix_batch)

Matriz de Confusão para o metodo do gradiente batch:
 [[0 9]
 [0 9]]


In [316]:
precision_batch,recall_batch,fscore_batch,support_batch = precision_recall_fscore_support(y_test,y_pred)
print("Precisao para o metodo do gradiente batch: ", precision_batch)
print("Recall para o metodo do gradiente batch: ", recall_batch)
print("F-Score para o metodo do gradiente batch: ", fscore_batch)
print("Support para o metodo do gradiente batch: ", support_batch)

Precisao para o metodo do gradiente batch:  [0.  0.5]
Recall para o metodo do gradiente batch:  [0. 1.]
F-Score para o metodo do gradiente batch:  [0.         0.66666667]
Support para o metodo do gradiente batch:  [9 9]


/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [317]:
acc_batch = accuracy_score(y_test, y_pred)
print("Acuracia para o metodo do gradiente batch: ", acc_batch)

Acuracia para o metodo do gradiente batch:  0.5
